### ISSUE TITLE
Mark depreciated

### ISSUE THREAD

**Issue by chrbala** [mblarsen/resume-linkedin#1]
Hi,

LinkedIn now requires special permissions for r_fullprofile access. It's unlikely anyone trying to make resumes has these permissions as LinkedIn has a seemingly tight approval process.

Please mark this as depreciated as the full profile contains most of the information that this resume generator accesses.

Thanks

**Comment by mblarsen** [comment]
Done (on NPM as well)

**Comment by chrbala** [comment]
Thanks! This'll save some time for passers-by.
